const SB_URL='https://wlediyikwdcmrkndgcfh.supabase.co'; const SB_KEY='sb_publishable_MSBkB_QvzOZ911uC7VEdsQ_JwQyhI0v';
const sb=supabase.createClient(SB_URL,SB_KEY); let me=null, view='tables', selectedTable=null, selectedSession=null, menu=[], tables=[], sessions=[], items=[], refreshTimer=null, refreshing=false;
const $=s=>document.querySelector(s); const money=n=>'₹'+Number(n||0).toLocaleString('en-IN'); function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function emailsFor(login){login=login.trim().toLowerCase();return (login==='jaypithva1803'||login==='jay')?['jpithva01@gmail.com','jay@ldp-pos.invalid']:[login+'@love-dot-point.invalid']}
async function login(){const login=$('#loginId').value.trim().toLowerCase(),password=$('#loginPw').value;if(!login||!password)return toast('Login ID and password required');let lastError=null;for(const email of emailsFor(login)){const {error}=await sb.auth.signInWithPassword({email,password});if(!error){await boot();return}lastError=error}toast(lastError?.message||'Login failed')}
async function logout(){await sb.auth.signOut();location.reload()}
async function boot(){const {data:{user}}=await sb.auth.getUser();if(!user)return;const {data,error}=await sb.from('staff_profiles').select('*').eq('auth_user_id',user.id).single();if(error||!data){toast('Staff profile not linked');return}me=data;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');const roleLabel=me.role==='owner'?'Owner':me.role==='cashier'?'Billing Cashier':'Waiter';$('#who').textContent=me.name+' · '+roleLabel;if(me.role==='cashier'){view='cashierqueue';renderNav();if(typeof window.renderCashierQueue==='function')await window.renderCashierQueue();return}renderNav();await refreshAll();if(me.role==='waiter'){const active=tables.filter(t=>t.status==='occupied'&&t.assigned_waiter_id===me.id);if(active.length===1){selectedTable=active[0].table_no;selectedSession=active[0].active_session_id;await refreshAll();view='menu';renderNav()}}render();subscribe();startTableClock()}
function navs(){if(me.role==='owner')return [['dashboard','Dashboard'],['tables','Live Tables'],['staff','Waiters'],['menumanager','Menu'],['history','Sales / Reports']];if(me.role==='cashier')return [['cashierqueue','Print Queue'],['cashierreports','Reports']];return [['tables','My Tables'],['menu','Take Order'],['history','History / Reports']]}
function renderNav(){const list=navs();const h=list.map(x=>`<button class="navbtn ${view===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('');$('#side').innerHTML=h;$('#mobilebar').innerHTML=list.map(x=>`<button class="${view===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('')}
function go(v){if(me.role==='owner'&&v==='menu')v='tables';if(me.role==='waiter'&&['dashboard','staff','menumanager'].includes(v))v='tables';if(me.role==='cashier'&&!['cashierqueue','cashierreports'].includes(v))v='cashierqueue';view=v;window.scrollTo({top:0,behavior:'smooth'});renderNav();render()}
async function refreshAll(){if(refreshing)return;refreshing=true;try{let [t,s,m]=await Promise.all([sb.from('restaurant_tables').select('*,staff_profiles:assigned_waiter_id(name)').order('table_no'),sb.from('table_sessions').select('*,restaurant_tables(table_no),staff_profiles:waiter_id(name)').order('started_at',{ascending:false}).limit(500),sb.from('menu_items').select('*').eq('active',true).order('category').order('name')]);tables=t.data||[];sessions=s.data||[];menu=m.data||[];if(selectedSession){const q=await sb.from('order_items').select('*').eq('session_id',selectedSession).order('created_at');items=q.data||[]}else items=[]}finally{refreshing=false}}
function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(async()=>{await refreshAll();if(view!=='menumanager'&&view!=='history'&&view!=='staff')render()},220)}
function subscribe(){sb.removeAllChannels();sb.channel('pos-live').on('postgres_changes',{event:'*',schema:'public',table:'restaurant_tables'},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'table_sessions'},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'order_items'},scheduleRefresh).on('postgres_changes',{event:'*',schema:'public',table:'menu_items'},async()=>{await refreshAll();if(view==='menu')renderMenu()}).subscribe()}
function head(title,sub=''){return `<div class="head"><div><h2>${title}</h2><div class="note">${sub}</div></div></div>`}
function render(){if(!me)return;if(me.role==='cashier'){if(view==='cashierreports'&&typeof window.renderCashierReports==='function')return window.renderCashierReports();if(typeof window.renderCashierQueue==='function')return window.renderCashierQueue();return}if(view==='dashboard'&&me.role==='owner')renderDashboard();else if(view==='tables')renderTables();else if(view==='menu'&&me.role==='waiter')renderMenu();else if(view==='staff'&&me.role==='owner')renderStaff();else if(view==='menumanager'&&me.role==='owner')renderMenuManager();else renderHistory()}
function renderDashboard(){const today=new Date().toDateString();const done=sessions.filter(s=>s.status==='finished'&&new Date(s.finished_at).toDateString()===today);const sales=done.reduce((a,b)=>a+Number(b.total_amount||0),0);$('#main').innerHTML=head('Owner Dashboard','Today’s live restaurant operations, table activity and sales at a glance.')+`<div class="kpis"><div class="kpi"><span>Today Sales</span><b>${money(sales)}</b></div><div class="kpi"><span>Active Tables</span><b>${tables.filter(t=>t.status==='occupied').length}</b></div><div class="kpi"><span>Completed Today</span><b>${done.length}</b></div><div class="kpi"><span>Active Menu Items</span><b>${menu.length}</b></div></div>`+tableHtml()}
function sessionForTable(t){return sessions.find(s=>s.status==='active'&&(s.id===t.active_session_id||s.table_id===t.id))}
function durationText(startedAt){if(!startedAt)return '0 Min';const ms=Math.max(0,Date.now()-new Date(startedAt).getTime());const mins=Math.floor(ms/60000);if(mins<60)return `${mins} Min`;const h=Math.floor(mins/60),m=mins%60;return m?`${h}h ${m}m`:`${h}h`}
function tableHtml(){return `<div class="tablegrid">${tables.map(t=>{const mine=t.assigned_waiter_id===me.id;const assigned=t.status==='occupied'?(t.staff_profiles?.name||'Assigned waiter'):(me.role==='owner'?'Ready for service':'Tap to assign');const click=me.role==='owner'?(t.status==='occupied'?`onclick="viewOwnerTable(${t.table_no})"`:''):`onclick="openTable(${t.table_no})"`;const s=t.status==='occupied'?sessionForTable(t):null;const timer=t.status==='occupied'&&s?.started_at?`<div class="table-duration" data-start="${s.started_at}" style="margin-top:8px;font-weight:800;font-size:13px">⏱ ${durationText(s.started_at)}</div>`:'';return `<button class="tablecard ${t.status==='occupied'?'occupied':''} ${mine?'mine':''} ${me.role==='owner'?'owner-view':''}" ${click}><span class="status">${t.status==='occupied'?'Occupied':'Available'}</span><div class="tn">Table ${t.table_no}</div><div class="meta">Capacity: ${t.capacity_label||'-'}<br>${t.status==='occupied'?'Waiter: '+assigned:assigned}</div>${timer}${me.role==='owner'&&t.status==='occupied'?'<div class="view-order-hint">Tap to view live order</div>':''}</button>`}).join('')}</div>`}
function renderTables(){$('#main').innerHTML=head(me.role==='owner'?'Live Tables':'My Tables',me.role==='waiter'?'Available table par tap karke Assign to Me karein. Occupied table par live service time dikhai dega. Sirf aapke assigned orders accessible hain.':'Live floor status, assigned waiter aur service duration. Occupied table par tap karke current order dekhein.')+tableHtml()}
function startTableClock(){if(window.__tableClock)return;window.__tableClock=setInterval(()=>{document.querySelectorAll('.table-duration[data-start]').forEach(el=>{el.textContent='⏱ '+durationText(el.dataset.start)})},15000)}
