const SB_URL='https://wlediyikwdcmrkndgcfh.supabase.co'; const SB_KEY='sb_publishable_MSBkB_QvzOZ911uC7VEdsQ_JwQyhI0v';
const sb=supabase.createClient(SB_URL,SB_KEY); let me=null, view='tables', selectedTable=null, selectedSession=null, menu=[], tables=[], sessions=[], items=[];
const $=s=>document.querySelector(s); const money=n=>'₹'+Number(n||0).toLocaleString('en-IN'); function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function emailFor(login){login=login.trim().toLowerCase();return (login==='jaypithva1803'||login==='jay')?'jay@ldp-pos.invalid':login+'@love-dot-point.invalid'}
async function login(){const login=$('#loginId').value.trim().toLowerCase(),password=$('#loginPw').value; if(!login||!password)return toast('Login ID and password required'); const {data,error}=await sb.auth.signInWithPassword({email:emailFor(login),password}); if(error)return toast(error.message); await boot();}
async function logout(){await sb.auth.signOut();location.reload()}
async function boot(){const {data:{user}}=await sb.auth.getUser(); if(!user)return; const {data,error}=await sb.from('staff_profiles').select('*').eq('auth_user_id',user.id).single(); if(error||!data){toast('Staff profile not linked');return} me=data; $('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#who').textContent=me.name+' · '+(me.role==='owner'?'Owner':'Waiter'); renderNav(); await refreshAll(); const active=tables.filter(t=>t.status==='occupied'&&(me.role==='owner'||t.assigned_waiter_id===me.id)); if(active.length===1){selectedTable=active[0].table_no;selectedSession=active[0].active_session_id;await refreshAll();view='menu';renderNav();} render(); subscribe();}
function navs(){return me.role==='owner'?[['dashboard','Dashboard'],['tables','Live Tables'],['menu','Take Order'],['staff','Waiters'],['history','Sales / History']]:[['tables','My Tables'],['menu','Take Order'],['history','My History']]}
function renderNav(){const h=navs().map(x=>`<button class="navbtn ${view===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('');$('#side').innerHTML=h;$('#mobilebar').innerHTML=navs().slice(0,4).map(x=>`<button class="${view===x[0]?'active':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('')}
function go(v){view=v;renderNav();render()}
async function refreshAll(){let [t,s,m]=await Promise.all([sb.from('restaurant_tables').select('*,staff_profiles:assigned_waiter_id(name)').order('table_no'),sb.from('table_sessions').select('*,restaurant_tables(table_no),staff_profiles:waiter_id(name)').order('started_at',{ascending:false}).limit(300),sb.from('menu_items').select('*').eq('active',true).order('category').order('name')]); tables=t.data||[];sessions=s.data||[];menu=m.data||[]; if(selectedSession){const q=await sb.from('order_items').select('*').eq('session_id',selectedSession).order('created_at');items=q.data||[]}else items=[]}
function subscribe(){sb.channel('pos-live').on('postgres_changes',{event:'*',schema:'public',table:'restaurant_tables'},async()=>{await refreshAll();render()}).on('postgres_changes',{event:'*',schema:'public',table:'table_sessions'},async()=>{await refreshAll();render()}).on('postgres_changes',{event:'*',schema:'public',table:'order_items'},async()=>{await refreshAll();render()}).subscribe()}
function head(title,sub=''){return `<div class="head"><div><h2>${title}</h2><div class="note">${sub}</div></div></div>`}
function render(){if(!me)return;if(view==='dashboard')renderDashboard();else if(view==='tables')renderTables();else if(view==='menu')renderMenu();else if(view==='staff')renderStaff();else renderHistory()}
function renderDashboard(){const today=new Date().toDateString();const done=sessions.filter(s=>s.status==='finished'&&new Date(s.finished_at).toDateString()===today);const sales=done.reduce((a,b)=>a+Number(b.total_amount||0),0);$('#main').innerHTML=head('Owner Dashboard','Live restaurant overview')+`<div class="kpis"><div class="kpi"><span>Today Sales</span><b>${money(sales)}</b></div><div class="kpi"><span>Active Tables</span><b>${tables.filter(t=>t.status==='occupied').length}</b></div><div class="kpi"><span>Completed Today</span><b>${done.length}</b></div><div class="kpi"><span>Menu Items</span><b>${menu.length}</b></div></div>`+tableHtml()}
function tableHtml(){return `<div class="tablegrid">${tables.map(t=>{const mine=t.assigned_waiter_id===me.id;return `<button class="tablecard ${t.status==='occupied'?'occupied':''} ${mine?'mine':''}" onclick="openTable(${t.table_no})"><span class="status">${t.status}</span><div class="tn">Table ${t.table_no}</div><div class="meta">Capacity: ${t.capacity_label||'-'}<br>${t.status==='occupied'?(t.staff_profiles?.name||'Assigned'):'Tap to assign'}</div></button>`}).join('')}</div>`}
function renderTables(){$('#main').innerHTML=head(me.role==='owner'?'Live Tables':'My Active Tables & Available Tables',me.role==='waiter'?'Other waiter orders are hidden by server permissions.':'Owner can view every table.')+tableHtml()}
