function dateInputValue(d){const x=new Date(d);const off=x.getTimezoneOffset();return new Date(x.getTime()-off*60000).toISOString().slice(0,10)}
function reportDateBounds(){const today=new Date();const from=window.ownerReportFrom||dateInputValue(new Date(today.getTime()-6*86400000));const to=window.ownerReportTo||dateInputValue(today);return {from,to}}
function inDateRange(s,from,to){if(!s.finished_at)return false;const d=new Date(s.finished_at);const a=new Date(from+'T00:00:00');const b=new Date(to+'T23:59:59.999');return d>=a&&d<=b}
function safeCsv(v){const s=String(v??'');return '"'+s.replaceAll('"','""')+'"'}
function downloadOwnerReportCsv(list){const rows=[['Order No','Date/Time','Table','Waiter','Payment','Amount','Status']];list.forEach(s=>rows.push([s.order_no||'',s.finished_at?new Date(s.finished_at).toLocaleString('en-IN'):'',s.restaurant_tables?.table_no||'',s.staff_profiles?.name||'',s.payment_mode||'',Number(s.total_amount||0).toFixed(2),s.voided?'VOID':'COMPLETED']));const csv=rows.map(r=>r.map(safeCsv).join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='love-dot-point-sales-report.csv';a.click();URL.revokeObjectURL(a.href)}

async function fetchFinishedHistory(){
 let q=sb.from('table_sessions').select('id,table_id,waiter_id,status,started_at,finished_at,payment_mode,total_amount,order_no,voided,void_reason,voided_at').eq('status','finished').not('finished_at','is',null).order('finished_at',{ascending:false}).limit(1500);
 if(me.role!=='owner')q=q.eq('waiter_id',me.id);
 const {data,error}=await q;if(error)throw error;
 const tableMap={};(tables||[]).forEach(t=>tableMap[String(t.id)]={table_no:t.table_no});
 let staffMap={};
 if(me.role==='owner'){
  const {data:staff,error:se}=await sb.from('staff_profiles').select('id,name,role');
  if(!se)(staff||[]).forEach(x=>staffMap[String(x.id)]={name:x.name});
 }else staffMap[String(me.id)]={name:me.name};
 return (data||[]).map(x=>({...x,restaurant_tables:tableMap[String(x.table_id)]||{table_no:'-'},staff_profiles:staffMap[String(x.waiter_id)]||{name:'Former Waiter'}}));
}

function historyRecordCards(list,isOwner){return list.length?list.map(s=>`<div class="history-card ${s.voided?'voided-card':''}"><div class="history-card-top"><div><b>${esc(s.order_no||'Order')}</b><span>Table ${esc(s.restaurant_tables?.table_no||'-')}${isOwner?' · '+esc(s.staff_profiles?.name||'-'):''}</span></div><strong>${money(s.total_amount)}</strong></div><div class="history-meta"><span>${new Date(s.finished_at).toLocaleString('en-IN')}</span><span>${esc(s.payment_mode||'-')}</span>${s.voided?`<span class="void-badge">VOID</span>`:''}</div>${s.voided&&s.void_reason?`<div class="void-reason">Reason: ${esc(s.void_reason)}</div>`:''}<div class="history-actions"><button class="btn ghost" onclick="viewHistoricBill('${s.id}')">View / Reprint</button>${isOwner&&!s.voided?`<button class="btn danger-outline" onclick="voidHistoricBill('${s.id}','${esc(s.order_no||'Bill')}')">Void Bill</button>`:''}${isOwner&&s.voided?`<button class="btn ghost" onclick="restoreHistoricBill('${s.id}')">Restore</button>`:''}</div></div>`).join(''):'<div class="history-empty">No records found.</div>'}

async function viewHistoricBill(sessionId){const {data:s0,error}=await sb.from('table_sessions').select('*').eq('id',sessionId).single();if(error)return toast(error.message);const t=(tables||[]).find(x=>String(x.id)===String(s0.table_id));let waiterName=me.name;if(me.role==='owner'){const {data:w}=await sb.from('staff_profiles').select('name').eq('id',s0.waiter_id).maybeSingle();waiterName=w?.name||'Former Waiter'}const s={...s0,restaurant_tables:{table_no:t?.table_no||'-'},staff_profiles:{name:waiterName}};const {data:order,error:oe}=await sb.from('order_items').select('*').eq('session_id',sessionId).order('created_at');if(oe)return toast(oe.message);const rows=(order||[]).map((i,idx)=>`<tr><td>${idx+1}</td><td>${esc(i.item_name)}${i.note?`<small>${esc(i.note)}</small>`:''}</td><td class="num">${i.qty}</td><td class="num">${Number(i.unit_price).toFixed(2)}</td><td class="num">${(Number(i.unit_price)*i.qty).toFixed(2)}</td></tr>`).join('');$('#modalbox').innerHTML=`<div class="bill-modal-head"><div><h2>${s.voided?'VOID BILL':'Bill Reprint'}</h2><div class="note">Historical bill · read only</div></div><button class="btn ghost" onclick="closeModal()">Close</button></div><div class="receipt ${s.voided?'receipt-void':''}" id="receiptPrint"><div class="receipt-head"><img class="receipt-logo" src="https://wlediyikwdcmrkndgcfh.supabase.co/functions/v1/pos-logo"><div class="receipt-title">LOVE DOT POINT RESTAURANT</div><div class="receipt-sub">PURE VEG · A.C. RESTAURANT</div><div class="receipt-address">41, 42, 43, Madhav Mall, Opp. Ratanba School,<br>Thakkarbapa Nagar, Ahmedabad - 382350</div><div class="receipt-phone">M: 9016889544</div>${s.voided?'<div class="void-stamp">VOID</div>':''}</div><div class="receipt-meta"><div><span>Table No.</span><b>${s.restaurant_tables?.table_no||'-'}</b></div><div><span>Order No.</span><b>${esc(s.order_no||'-')}</b></div><div><span>Date</span><b>${new Date(s.finished_at).toLocaleDateString('en-IN')}</b></div><div><span>Time</span><b>${new Date(s.finished_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</b></div><div><span>Waiter</span><b>${esc(s.staff_profiles?.name||'-')}</b></div></div><table class="bill-table"><thead><tr><th>#</th><th>Item</th><th class="num">Qty</th><th class="num">Rate</th><th class="num">Amount</th></tr></thead><tbody>${rows}</tbody></table><div class="bill-summary"><div><span>GST</span><b>Not Applicable</b></div><div class="grand"><span>GRAND TOTAL</span><b>${money(s.total_amount)}</b></div><div><span>Payment</span><b>${esc(s.payment_mode||'-')}</b></div></div>${s.voided?`<div class="void-reason-print">VOID REASON: ${esc(s.void_reason||'-')}</div>`:''}<div class="receipt-footer">Thank You! Visit Again</div></div><div class="bill-actions"><button class="btn" onclick="window.print()">Print / Reprint Bill</button></div>`;$('#modal').classList.remove('hidden')}
async function voidHistoricBill(id,label){const reason=prompt(`Void ${label}\nReason likhiye (minimum 3 characters):`);if(reason===null)return;if(reason.trim().length<3)return toast('Void reason required');if(!confirm('Is bill ko VOID mark karna hai? Sales reports se amount exclude ho jayega.'))return;try{await adminCall({action:'void_bill',session_id:id,reason:reason.trim()});toast('Bill voided');renderHistory()}catch(e){toast(e.message)}}
async function restoreHistoricBill(id){if(!confirm('Is void bill ko restore karke sales me wapas include karna hai?'))return;try{await adminCall({action:'restore_void',session_id:id});toast('Bill restored');renderHistory()}catch(e){toast(e.message)}}

function renderDashboard(){const today=new Date().toDateString();const done=sessions.filter(s=>s.status==='finished'&&!s.voided&&s.finished_at&&new Date(s.finished_at).toDateString()===today);const sales=done.reduce((a,b)=>a+Number(b.total_amount||0),0);const active=tables.filter(t=>t.status==='occupied').length;$('#main').innerHTML=head('Owner Dashboard','Live overview · void bills excluded')+`<div class="kpis"><div class="kpi"><span>Today Net Sales</span><b>${money(sales)}</b></div><div class="kpi"><span>Active Tables</span><b>${active}</b></div><div class="kpi"><span>Completed Today</span><b>${done.length}</b></div><div class="kpi"><span>Active Menu Items</span><b>${menu.length}</b></div></div><div class="quick-actions card"><button class="btn" onclick="go('tables')">Live Tables</button><button class="btn alt" onclick="go('menuadmin')">Menu Management</button><button class="btn alt" onclick="go('staff')">Waiters</button><button class="btn alt" onclick="go('history')">Reports & Bills</button></div>${tableHtml()}`}
