function navs(){return me.role==='owner'?[['dashboard','Dashboard'],['tables','Live Tables'],['menumanager','Menu'],['staff','Waiters'],['history','Reports']]:[['tables','My Tables'],['menu','Take Order'],['history','History']]}
function render(){if(!me)return;if(view==='dashboard'&&me.role==='owner')renderDashboard();else if(view==='tables')renderTables();else if(view==='menu'&&me.role==='waiter')renderMenu();else if(view==='menumanager'&&me.role==='owner')renderMenuManager();else if(view==='staff'&&me.role==='owner')renderStaff();else renderHistory()}
function go(v){if(me.role==='owner'&&v==='menu')v='tables';if(me.role==='waiter'&&(v==='menumanager'||v==='staff'||v==='dashboard'))v='tables';view=v;renderNav();render()}

async function renderHistory(){
 const isOwner=me.role==='owner';$('#main').innerHTML=head(isOwner?'Sales / Reports':'My Table History & Reports',isOwner?'Date-wise sales, waiter ranking, bill reprint and void control.':'Aapke saare past completed tables aur bills.')+'<div class="card">Loading...</div>';
 let all=[];try{all=await fetchFinishedHistory()}catch(e){toast(e.message);return}
 if(!isOwner){
  const range=window.historyRange||'all';const now=new Date();let start=null;if(range==='today')start=new Date(now.getFullYear(),now.getMonth(),now.getDate());if(range==='7d')start=new Date(now.getTime()-7*86400000);if(range==='30d')start=new Date(now.getTime()-30*86400000);const list=start?all.filter(s=>new Date(s.finished_at)>=start):all;const valid=list.filter(s=>!s.voided);const total=valid.reduce((a,b)=>a+Number(b.total_amount||0),0);const cash=valid.filter(s=>(s.payment_mode||'').toLowerCase()==='cash').reduce((a,b)=>a+Number(b.total_amount||0),0);const upi=valid.filter(s=>(s.payment_mode||'').toLowerCase()==='upi').reduce((a,b)=>a+Number(b.total_amount||0),0);const avg=valid.length?total/valid.length:0;
  $('#main').innerHTML=head('My Table History & Reports','Past tables default All History · void bills net sales me count nahi honge.')+`<div class="history-filters"><button class="${range==='today'?'active':''}" onclick="window.historyRange='today';renderHistory()">Today</button><button class="${range==='7d'?'active':''}" onclick="window.historyRange='7d';renderHistory()">7 Days</button><button class="${range==='30d'?'active':''}" onclick="window.historyRange='30d';renderHistory()">30 Days</button><button class="${range==='all'?'active':''}" onclick="window.historyRange='all';renderHistory()">All History</button></div><div class="report-grid advanced-reports">${reportCard('Tables Served',valid.length,'Completed')}${reportCard('Total Sales',money(total),'Net sales')}${reportCard('Average Bill',money(avg),'Per table')}${reportCard('Cash',money(cash),'Collection')}${reportCard('UPI',money(upi),'Collection')}</div><div class="history-section-title"><h3>Past Tables</h3><span>${list.length} records</span></div><div class="history-list">${historyRecordCards(list,false)}</div>`;return
 }
 const {from,to}=reportDateBounds();const search=(window.billSearch||'').trim().toLowerCase();let list=all.filter(s=>inDateRange(s,from,to));if(search)list=list.filter(s=>(s.order_no||'').toLowerCase().includes(search)||String(s.restaurant_tables?.table_no||'').includes(search)||(s.staff_profiles?.name||'').toLowerCase().includes(search));window.currentOwnerReportList=list;const valid=list.filter(s=>!s.voided);const total=valid.reduce((a,b)=>a+Number(b.total_amount||0),0);const cash=valid.filter(s=>(s.payment_mode||'').toLowerCase()==='cash').reduce((a,b)=>a+Number(b.total_amount||0),0);const upi=valid.filter(s=>(s.payment_mode||'').toLowerCase()==='upi').reduce((a,b)=>a+Number(b.total_amount||0),0);const voids=list.filter(s=>s.voided).length;const perf={};valid.forEach(s=>{const n=s.staff_profiles?.name||'Unknown';if(!perf[n])perf[n]={tables:0,sales:0};perf[n].tables++;perf[n].sales+=Number(s.total_amount||0)});const ranking=Object.entries(perf).sort((a,b)=>b[1].sales-a[1].sales);
 $('#main').innerHTML=head('Sales / Reports','Advanced owner control · void bills net sales se excluded')+`<div class="owner-report-toolbar card"><div><label>From</label><input class="field" type="date" value="${from}" onchange="window.ownerReportFrom=this.value;renderHistory()"></div><div><label>To</label><input class="field" type="date" value="${to}" onchange="window.ownerReportTo=this.value;renderHistory()"></div><div class="report-search"><label>Search Bill / Table / Waiter</label><input class="field" placeholder="Order no / table / waiter" value="${esc(window.billSearch||'')}" oninput="window.billSearch=this.value;renderHistory()"></div><button class="btn ghost export-btn" onclick="downloadOwnerReportCsv(window.currentOwnerReportList||[])">Export CSV</button></div><div class="report-grid advanced-reports">${reportCard('Net Sales',money(total),'Void excluded')}${reportCard('Completed Bills',valid.length,'Valid bills')}${reportCard('Cash',money(cash),'Collection')}${reportCard('UPI',money(upi),'Collection')}${reportCard('Void Bills',voids,'Cancelled')}${reportCard('Average Bill',money(valid.length?total/valid.length:0),'Per bill')}</div><div class="ranking-panel card"><div class="history-section-title"><h3>Waiter Performance Ranking</h3><span>${ranking.length} waiters</span></div>${ranking.length?ranking.map((r,i)=>`<div class="ranking-row"><span class="rank-no">#${i+1}</span><div><b>${esc(r[0])}</b><small>${r[1].tables} tables served</small></div><strong>${money(r[1].sales)}</strong></div>`).join(''):'<div class="note">No sales in selected period.</div>'}</div><div class="history-section-title"><h3>Bills & Table History</h3><span>${list.length} records</span></div><div class="history-list">${historyRecordCards(list,true)}</div>`
}
