/* Owner Customer Pending / Parcel Credit Ledger */
(function(){
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>new Date(d+'T00:00:00').toLocaleDateString('en-GB');
const amt=n=>money(Number(n||0));
let customers=[],selected=null,ledger=[];
async function loadCustomers(){const {data,error}=await sb.from('customer_accounts').select('*').eq('active',true).order('name');if(error)throw error;customers=data||[]}
async function loadLedger(id){const {data,error}=await sb.from('customer_ledger').select('*').eq('customer_id',id).order('entry_date',{ascending:false}).order('id',{ascending:false});if(error)throw error;ledger=data||[]}
function totals(){const bills=ledger.filter(x=>x.entry_type==='bill').reduce((a,x)=>a+Number(x.amount),0),paid=ledger.filter(x=>x.entry_type==='payment').reduce((a,x)=>a+Number(x.amount),0);return {bills,paid,pending:bills-paid}}
window.renderCustomerLedger=async function(){
 if(!me||me.role!=='owner')return;
 $('#main').innerHTML=head('Customer Pending Bills','Parcel / customer credit ledger — bill, payment, part-payment and live pending balance.')+'<div class="card">Loading...</div>';
 try{await loadCustomers();if(!selected&&customers[0])selected=customers[0].id;if(selected&&!customers.some(x=>x.id===selected))selected=customers[0]?.id||null;if(selected)await loadLedger(selected);else ledger=[]}catch(e){$('#main').innerHTML=head('Customer Pending Bills')+'<div class="card">Ledger database initializing. '+esc(e.message)+'</div>';return}
 const totalPending=await overallPending();
 const list=customers.map(c=>{const active=String(c.id)===String(selected);return '<button class="cl-client '+(active?'active':'')+'" onclick="selectCustomerLedger('+c.id+')"><b>'+esc(c.name)+'</b><span>'+(esc(c.phone||'No phone'))+'</span></button>'}).join('');
 let detail='<div class="cl-empty">Customer add karke uska bill/payment ledger start karein.</div>';
 if(selected){const c=customers.find(x=>x.id===selected),t=totals();detail='<div class="cl-detail-head"><div><h3>'+esc(c.name)+'</h3><span>'+esc(c.phone||'')+'</span></div><button class="btn ghost" onclick="editCustomerLedger('+c.id+')">Edit Customer</button></div><div class="cl-kpis"><div><span>Total Bills</span><b>'+amt(t.bills)+'</b></div><div><span>Total Paid</span><b>'+amt(t.paid)+'</b></div><div class="pending"><span>Total Pending</span><b>'+amt(t.pending)+'</b></div></div><div class="cl-actions"><button class="btn" onclick="addCustomerBill()">+ Add Bill</button><button class="btn ghost" onclick="addCustomerPayment()">+ Add Payment</button></div><div class="cl-ledger">'+(ledger.length?ledger.map((x,i)=>'<div class="cl-row '+x.entry_type+'"><div class="cl-no">'+(ledger.length-i)+'</div><div><b>'+(x.entry_type==='bill'?esc(x.service_type||'Parcel'):'Paid')+'</b><span>'+fmt(x.entry_date)+(x.note?' · '+esc(x.note):'')+'</span></div><strong>'+(x.entry_type==='bill'?'+ ':'− ')+amt(x.amount)+'</strong><button class="cl-del" onclick="deleteCustomerEntry('+x.id+')">Delete</button></div>').join(''):'<div class="note">Abhi koi bill/payment entry nahi hai.</div>')+'</div>';
 }
 $('#main').innerHTML=head('Customer Pending Bills','Customer-wise Parcel/Baki account. Part payment ke baad pending amount automatic calculate hota hai.')+'<div class="cl-top"><div class="cl-overall"><span>All Customers Pending</span><b>'+amt(totalPending)+'</b></div><button class="btn" onclick="addCustomerLedger()">+ New Customer</button></div><div class="cl-layout"><div class="card cl-sidebar"><input id="clSearch" class="field" placeholder="Search customer..." oninput="filterCustomerLedger(this.value)"><div id="clClientList">'+(list||'<div class="note">No customers</div>')+'</div></div><div class="card cl-detail">'+detail+'</div></div>';
};
async function overallPending(){if(!customers.length)return 0;const ids=customers.map(x=>x.id);const {data}=await sb.from('customer_ledger').select('customer_id,entry_type,amount').in('customer_id',ids);return (data||[]).reduce((a,x)=>a+(x.entry_type==='bill'?Number(x.amount):-Number(x.amount)),0)}
window.selectCustomerLedger=async id=>{selected=id;await renderCustomerLedger()};
window.filterCustomerLedger=q=>{q=String(q||'').toLowerCase();document.querySelectorAll('.cl-client').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q)?'':'none')};
window.addCustomerLedger=async function(){const name=prompt('Customer name');if(!name?.trim())return;const phone=prompt('Mobile number (optional)')||null;const {data,error}=await sb.from('customer_accounts').insert({name:name.trim(),phone:phone?.trim()||null,created_by:me.id}).select('*').single();if(error)return toast(error.message);selected=data.id;toast('Customer added');renderCustomerLedger()};
window.editCustomerLedger=async function(id){const c=customers.find(x=>x.id===id);if(!c)return;const name=prompt('Customer name',c.name);if(!name?.trim())return;const phone=prompt('Mobile number',c.phone||'');const {error}=await sb.from('customer_accounts').update({name:name.trim(),phone:phone?.trim()||null}).eq('id',id);if(error)return toast(error.message);toast('Customer updated');renderCustomerLedger()};
window.addCustomerBill=async function(){const amount=Number(prompt('Bill amount'));if(!(amount>0))return;const date=prompt('Bill date (YYYY-MM-DD)',new Date().toISOString().slice(0,10));if(!/^\d{4}-\d{2}-\d{2}$/.test(date||''))return toast('Valid date required');const type=prompt('Type: Parcel / Dine-In / Other','Parcel')||'Parcel';const service=['Parcel','Dine-In','Other'].includes(type)?type:'Other';const note=prompt('Bill note / reference (optional)')||null;const {error}=await sb.from('customer_ledger').insert({customer_id:selected,entry_type:'bill',entry_date:date,service_type:service,amount,note,created_by:me.id});if(error)return toast(error.message);toast('Bill added');renderCustomerLedger()};
window.addCustomerPayment=async function(){const amount=Number(prompt('Paid amount'));if(!(amount>0))return;const date=prompt('Payment date (YYYY-MM-DD)',new Date().toISOString().slice(0,10));if(!/^\d{4}-\d{2}-\d{2}$/.test(date||''))return toast('Valid date required');const note=prompt('Payment note (Cash/UPI/reference optional)')||null;const {error}=await sb.from('customer_ledger').insert({customer_id:selected,entry_type:'payment',entry_date:date,service_type:'Other',amount,note,created_by:me.id});if(error)return toast(error.message);toast('Payment added — pending updated');renderCustomerLedger()};
window.deleteCustomerEntry=async id=>{if(!confirm('Ye ledger entry delete karni hai?'))return;const {error}=await sb.from('customer_ledger').delete().eq('id',id);if(error)return toast(error.message);toast('Entry deleted');renderCustomerLedger()};
})();