(()=>{
function activeSession(t){return sessions.find(s=>s.status==='active'&&(String(s.id)===String(t.active_session_id)||String(s.table_id)===String(t.id)))||null}
function elapsed(start){if(!start)return '0 Min';const min=Math.max(0,Math.floor((Date.now()-new Date(start).getTime())/60000));if(min<60)return `${min} Min`;const h=Math.floor(min/60),m=min%60;return m?`${h}h ${m}m`:`${h}h`}
function timerHtml(t){if(t.status!=='occupied')return '';const s=activeSession(t);return `<div class="floor-live-time" data-session-start="${s?.started_at||''}"><span>● LIVE</span><b>⏱ ${elapsed(s?.started_at)}</b></div>`}
function floorCards(){return `<div class="tablegrid floor-v3-grid">${tables.map(t=>{const mine=t.assigned_waiter_id===me.id,occupied=t.status==='occupied',waiter=t.staff_profiles?.name||'Assigned waiter';let click='';if(me.role==='owner'&&occupied)click=`onclick="viewOwnerTable(${t.table_no})"`;if(me.role==='waiter')click=`onclick="openTable(${t.table_no})"`;return `<button class="tablecard ${occupied?'occupied':''} ${mine?'mine':''} ${me.role==='owner'?'owner-view':''}" ${click}><div class="floor-card-top"><span class="status">${occupied?'Occupied':'Available'}</span>${occupied?timerHtml(t):''}</div><div class="tn">Table ${t.table_no}</div><div class="meta">Capacity: ${t.capacity_label||'-'}<br>${occupied?`Waiter: ${waiter}`:(me.role==='waiter'?'Tap to assign this table':'Ready for service')}</div>${me.role==='owner'&&occupied?'<div class="view-order-hint">Tap to view live order</div>':''}</button>`}).join('')}</div>`}
window.tableHtml=floorCards;
window.renderTables=function(){if(me.role==='owner'){const occupied=tables.filter(t=>t.status==='occupied').length;$('#main').innerHTML=head('Live Table Floor',`${occupied} occupied · ${tables.length-occupied} available · Service time starts when a table is assigned.`)+floorCards();return}const mine=tables.filter(t=>t.status==='occupied'&&t.assigned_waiter_id===me.id);const available=tables.filter(t=>t.status==='available');$('#main').innerHTML=`<div class="waiter-home"><div><span class="waiter-eyebrow">WAITER FLOOR</span><h2>Welcome, ${me.name}</h2><p>Apne active tables manage karein aur available table par tap karke naya dine-in order start karein.</p></div><div class="waiter-home-stats"><div><span>My Active Tables</span><b>${mine.length}</b></div><div><span>Available Tables</span><b>${available.length}</b></div></div></div><div class="floor-section-head"><div><h3>Table Floor</h3><p>Occupied table par assignment se ab tak ka live service time dikh raha hai.</p></div><span class="floor-legend">● Live Timer</span></div>${floorCards()}`}
function updateClocks(){document.querySelectorAll('.floor-live-time[data-session-start]').forEach(el=>{const b=el.querySelector('b');if(b)b.textContent='⏱ '+elapsed(el.dataset.sessionStart)})}
function updateIdentity(){if(!me)return;const who=document.getElementById('who');if(!who)return;const role=me.role==='owner'?'Owner':'Waiter';who.innerHTML=`<span class="identity-role">${role}</span><span class="identity-name">${me.name}</span>`;who.setAttribute('aria-label',`${role}: ${me.name}`)}
setInterval(()=>{updateClocks();updateIdentity()},1000);document.addEventListener('DOMContentLoaded',()=>{updateIdentity();updateClocks()});
})();