// Shared live floor: all staff see live tables; only assigned waiter edits orders; owner can audited-force-close.
(function(){
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let waiterDirectory={},sessionMeta={};
  function minsSince(v){return v?Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000)):0}
  function elapsed(v){const m=minsSince(v);if(m<60)return `${m} Min`;const h=Math.floor(m/60),r=m%60;return r?`${h}h ${r}m`:`${h}h`}
  function getSession(t){return sessions.find(s=>String(s.id)===String(t.active_session_id))||sessionMeta[String(t.active_session_id)]||null}
  function waiterName(t,s){return waiterDirectory[String(t.assigned_waiter_id)]||t.staff_profiles?.name||s?.staff_profiles?.name||'Assigned waiter'}
  async function hydrateLiveMeta(){if(!me)return;const occupied=tables.filter(t=>t.status==='occupied');if(!occupied.length)return;try{const [{data:dir},{data:ss}]=await Promise.all([sb.rpc('live_waiter_directory'),sb.from('table_sessions').select('id,waiter_id,started_at,status').in('id',occupied.map(t=>t.active_session_id).filter(Boolean))]);waiterDirectory={};(dir||[]).forEach(w=>waiterDirectory[String(w.id)]=w.name);sessionMeta={};(ss||[]).forEach(s=>sessionMeta[String(s.id)]=s);occupied.forEach(t=>{const card=document.querySelector(`.tablecard[data-table-no="${t.table_no}"]`);if(!card)return;const s=getSession(t),name=waiterName(t,s),wn=card.querySelector('.shared-waiter-name'),tm=card.querySelector('.shared-live-time');if(wn)wn.textContent=name;if(tm&&s?.started_at){tm.dataset.start=s.started_at;tm.textContent='⏱ '+elapsed(s.started_at)}})}catch(e){console.warn('Live floor metadata refresh failed',e)}}

  async function openSharedTable(no){const t=tables.find(x=>x.table_no===no);if(!t)return;if(me.role==='owner'&&t.status==='occupied')return viewSharedTable(no);if(t.status==='available')return openTable(no);if(t.assigned_waiter_id===me.id)return openTable(no);return viewSharedTable(no)}
  window.openSharedTable=openSharedTable;
  window.ownerForceClosePrompt=function(sessionId,tableNo){if(me?.role!=='owner')return toast('Owner access required');document.getElementById('modalbox').innerHTML=`<div class="eyebrow">OWNER CONTROL · AUDITED ACTION</div><h2>Force Close Table ${tableNo}</h2><div class="note">Use only when a guest leaves, an order is abandoned, or the table must be released operationally. This will free the table and preserve the session as a voided audit record.</div><div class="formrow"><textarea id="forceCloseReason" class="field" rows="3" placeholder="Reason required, e.g. Guest left before billing"></textarea></div><div class="bill-actions"><button class="btn ghost" onclick="viewSharedTable(${tableNo})">Cancel</button><button class="btn red" onclick="ownerForceClose('${sessionId}',${tableNo})">Force Close & Release</button></div>`;document.getElementById('modal').classList.remove('hidden')};
  window.ownerForceClose=async function(sessionId,tableNo){const reason=(document.getElementById('forceCloseReason')?.value||'').trim();if(reason.length<3)return toast('Force close reason required');if(!confirm(`Force Close Table ${tableNo}?\n\nTable Available ho jayega. Order normal sale me count nahi hoga.`))return;const {error}=await sb.rpc('owner_force_close_table',{p_session_id:sessionId,p_reason:reason});if(error)return toast(error.message);closeModal();await refreshAll();view='tables';renderNav();render();toast(`Table ${tableNo} force closed · audit saved`)};

  window.viewSharedTable=async function(no){const t=tables.find(x=>x.table_no===no);if(!t||t.status!=='occupied'||!t.active_session_id)return toast('Table is available.');await hydrateLiveMeta();const s=getSession(t);const {data,error}=await sb.from('order_items').select('*').eq('session_id',t.active_session_id).order('created_at');if(error)return toast(error.message);const order=data||[],total=order.reduce((a,b)=>a+Number(b.unit_price)*b.qty,0),started=s?.started_at?new Date(s.started_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'}):'-',duration=s?.started_at?elapsed(s.started_at):'-',name=waiterName(t,s),owner=me.role==='owner';document.getElementById('modalbox').innerHTML=`<div class="shared-order-head"><div><div class="eyebrow">${owner?'OWNER CONTROL · LIVE TABLE':'VIEW ONLY · ANOTHER WAITER\'S TABLE'}</div><h2>Table ${no} · Live Order</h2><div class="note">Waiter: <b>${esc(name)}</b> · Started ${started} · ⏱ ${duration}</div></div><button class="btn ghost" onclick="closeModal()">Close</button></div><div class="owner-order-list">${order.length?order.map((i,idx)=>`<div class="owner-order-row"><span>${idx+1}</span><div><b>${esc(i.item_name)}</b>${i.note?`<small>${esc(i.note)}</small>`:''}</div><div>${i.qty} × ${money(i.unit_price)}</div><b>${money(Number(i.unit_price)*i.qty)}</b></div>`).join(''):'<div class="empty-order">No items added yet.</div>'}</div><div class="owner-total"><span>Current Order Value</span><b>${money(total)}</b></div>${owner?`<div class="shared-lock-note">Owner view is read-only for order items. Billing/order edits stay with the assigned waiter.</div><div class="bill-actions"><button class="btn red" onclick="ownerForceClosePrompt('${t.active_session_id}',${no})">Force Close / Release Table</button></div>`:`<div class="shared-lock-note">🔒 Read only — sirf ${esc(name)} is order ko change, bill ya finish kar sakte hain.</div>`}`;document.getElementById('modal').classList.remove('hidden')};

  window.tableHtml=function(){if(!me)return '';const owner=me.role==='owner';return `<div class="tablegrid">${tables.map(t=>{const mine=t.assigned_waiter_id===me.id,occupied=t.status==='occupied',s=occupied?getSession(t):null,name=occupied?waiterName(t,s):'Ready for dine-in',timer=occupied?`<div class="table-duration shared-live-time" data-start="${s?.started_at||''}">⏱ ${s?.started_at?elapsed(s.started_at):'Loading...'}</div>`:'',badge=occupied?(owner?'<div class="shared-view-badge">OWNER CONTROL · View live order</div>':(!mine?'<div class="shared-view-badge">VIEW ONLY · Tap to see order</div>':'<div class="mine-edit-badge">YOUR TABLE · Full Control</div>')):'<div class="mine-edit-badge">AVAILABLE · Tap to assign</div>';return `<button data-table-no="${t.table_no}" class="tablecard ${occupied?'occupied':''} ${mine?'mine':'shared-table'}" onclick="openSharedTable(${t.table_no})"><span class="status">${occupied?'Occupied':'Available'}</span><div class="tn">Table ${t.table_no}</div><div class="meta">Capacity: ${esc(t.capacity_label||'-')}<br>${occupied?`Waiter: <span class="shared-waiter-name">${esc(name)}</span>`:name}</div>${timer}${badge}</button>`}).join('')}</div>`};
  window.renderTables=function(){const owner=me.role==='owner';document.getElementById('main').innerHTML=head(owner?'Live Floor · Owner Control':'Live Table Floor',owner?'Real-time dine-in operations · view every active order, waiter and running time. Use Force Close only for abandoned/exception tables.':'All 15 dine-in tables are visible. Assigned tables have full order control; other waiter tables are view-only.')+tableHtml();setTimeout(hydrateLiveMeta,0)};
  setInterval(()=>document.querySelectorAll('.shared-live-time[data-start]').forEach(el=>{if(el.dataset.start)el.textContent='⏱ '+elapsed(el.dataset.start)}),1000);
})();
