/* Staff Salary & Leave Ledger */
(function(){
const e=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const ym=d=>{const x=d?new Date(d+'T00:00:00'):new Date();return x.getFullYear()+'-'+String(x.getMonth()+1).padStart(2,'0')};
const monthDate=m=>m+'-01'; const fmt=d=>new Date(d+'T00:00:00').toLocaleDateString('en-GB');
window.renderPayroll=async function(){
 const owner=me.role==='owner'; $('#main').innerHTML=head(owner?'Staff Salary & Leave':'My Salary & Leave','Monthly salary, Upad, Uchak Pagar, leave deduction and pending salary.')+'<div class="card">Loading...</div>';
 let staff=[]; if(owner){try{const j=await adminCall({action:'list_staff'});staff=(j.data||[]).filter(x=>x.role==='waiter'&&x.active&&!String(x.login_id||'').startsWith('removed_'))}catch(x){return toast(x.message)}}else staff=[me];
 const sid=window.payrollStaffId||(owner?staff[0]?.id:me.id); if(!sid)return $('#main').innerHTML=head('Staff Salary & Leave')+'<div class="card">No waiter found.</div>';
 window.payrollStaffId=sid; const month=window.payrollMonth||ym(); window.payrollMonth=month;
 const [{data:set},{data:led},{data:lev}]=await Promise.all([sb.from('staff_salary_settings').select('*').eq('staff_id',sid).maybeSingle(),sb.from('staff_salary_ledger').select('*').eq('staff_id',sid).eq('salary_month',monthDate(month)).order('entry_date'),sb.from('staff_leave_ledger').select('*').eq('staff_id',sid).eq('salary_month',monthDate(month)).order('leave_date')]);
 const salary=Number(set?.monthly_salary||0), leaves=(lev||[]).reduce((a,x)=>a+Number(x.days||1),0), perDay=salary/30, leaveDed=perDay*leaves, upad=(led||[]).filter(x=>x.entry_type==='upad').reduce((a,x)=>a+Number(x.amount),0), uchak=(led||[]).filter(x=>x.entry_type==='uchak').reduce((a,x)=>a+Number(x.amount),0), pending=Math.max(0,salary-leaveDed-upad-uchak); const person=staff.find(x=>x.id===sid)||me;
 const controls=`<div class="pay-toolbar card">${owner?`<select class="field" onchange="window.payrollStaffId=this.value;renderPayroll()">${staff.map(x=>`<option value="${x.id}" ${x.id===sid?'selected':''}>${e(x.name)}</option>`).join('')}</select>`:''}<input class="field" type="month" value="${month}" onchange="window.payrollMonth=this.value;renderPayroll()">${owner?`<button class="btn" onclick="setMonthlySalary('${sid}',${salary})">Set Salary</button>`:''}</div>`;
 const k=`<div class="pay-kpis"><div><span>Monthly Salary</span><b>${money(salary)}</b></div><div><span>Leave</span><b>${leaves} Day</b><small>${money(leaveDed)} deduction</small></div><div><span>Total Upad</span><b>${money(upad)}</b></div><div><span>Uchak Pagar</span><b>${money(uchak)}</b></div><div class="pending"><span>Salary Pending</span><b>${money(pending)}</b><small>${money(salary)} − ${money(leaveDed)} − ${money(upad+uchak)}</small></div></div>`;
 const add=`<div class="pay-add-grid"><div class="card"><h3>Add Upad / Uchak Pagar</h3><select id="payType" class="field"><option value="upad">Upad</option><option value="uchak">Uchak Pagar</option></select><input id="payAmount" class="field" type="number" min="1" placeholder="Amount"><input id="payDate" class="field" type="date" value="${new Date().toISOString().slice(0,10)}"><input id="payNote" class="field" placeholder="Note (optional)"><button class="btn" onclick="addPayrollEntry('${sid}')">Add Entry</button></div><div class="card"><h3>Add Leave</h3><input id="leaveDate" class="field" type="date" value="${new Date().toISOString().slice(0,10)}"><input id="leaveNote" class="field" placeholder="Reason / note (optional)"><button class="btn" onclick="addLeaveEntry('${sid}')">Add Leave</button></div></div>`;
 const rows=[...(led||[]).map(x=>({kind:x.entry_type==='upad'?'Upad':'Uchak Pagar',date:x.entry_date,amount:money(x.amount),id:x.id,table:'pay'})),...(lev||[]).map(x=>({kind:'Leave',date:x.leave_date,amount:Number(x.days||1)+' Day',id:x.id,table:'leave'}))].sort((a,b)=>b.date.localeCompare(a.date));
 const hist=`<div class="card pay-history"><div class="pay-history-head"><h3>${e(person.name)} · ${month}</h3><b>${rows.length} Entries</b></div>${rows.length?rows.map(x=>`<div class="pay-row"><div><b>${x.kind}</b><span>${fmt(x.date)}</span></div><strong>${x.amount}</strong>${owner?`<button class="pay-delete" onclick="deletePayrollEntry('${x.table}',${x.id})">Delete</button>`:''}</div>`).join(''):'<div class="note">Is month me koi entry nahi hai.</div>'}</div>`;
 $('#main').innerHTML=head(owner?'Staff Salary & Leave':'My Salary & Leave',owner?'Waiter-wise salary ledger. Delete permission sirf Owner ke paas hai.':'Apna salary, Upad/Uchak aur leave record. Delete sirf Owner kar sakta hai.')+controls+k+add+hist;
};
window.setMonthlySalary=function(sid,current){const v=prompt('Monthly salary enter karein',current||'');if(v===null)return;const n=Number(v);if(!Number.isFinite(n)||n<0)return toast('Valid salary enter karein');sb.from('staff_salary_settings').upsert({staff_id:sid,monthly_salary:n,updated_by:me.id,updated_at:new Date().toISOString()}).then(({error})=>{if(error)return toast(error.message);toast('Monthly salary updated');renderPayroll()})};
window.addPayrollEntry=async function(sid){const type=$('#payType').value,amount=Number($('#payAmount').value),date=$('#payDate').value;if(!amount||amount<=0||!date)return toast('Amount aur date required');const {error}=await sb.from('staff_salary_ledger').insert({staff_id:sid,entry_type:type,amount,entry_date:date,salary_month:monthDate(window.payrollMonth),note:$('#payNote').value.trim()||null,created_by:me.id});if(error)return toast(error.message);toast(type==='upad'?'Upad added':'Uchak Pagar added');renderPayroll()};
window.addLeaveEntry=async function(sid){const date=$('#leaveDate').value;if(!date)return toast('Leave date required');const {error}=await sb.from('staff_leave_ledger').insert({staff_id:sid,leave_date:date,salary_month:monthDate(window.payrollMonth),days:1,note:$('#leaveNote').value.trim()||null,created_by:me.id});if(error)return toast(error.code==='23505'?'Is date ki leave already added hai':error.message);toast('Leave added');renderPayroll()};
window.deletePayrollEntry=async function(type,id){if(me.role!=='owner')return toast('Delete sirf Owner kar sakta hai');if(!confirm('Ye entry delete karni hai?'))return;const table=type==='leave'?'staff_leave_ledger':'staff_salary_ledger';const {error}=await sb.from(table).delete().eq('id',id);if(error)return toast(error.message);toast('Entry deleted');renderPayroll()};
})();